version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MAX_QUEUE_LENGTH=100
      - API_KEY=${API_KEY:-default_key}
      - APP_DEBUG=${APP_DEBUG:-false}
      - STORAGE_PATH=${STORAGE_PATH:-local}
      # Optional S3 Configuration
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-}
      - S3_ENDPOINT=${S3_ENDPOINT:-}
      - S3_REGION=${S3_REGION:-}
      - S3_BUCKET=${S3_BUCKET:-}
      # Optional GCP Configuration
      - GCP_SA_CREDENTIALS=${GCP_SA_CREDENTIALS:-}
      - GCP_BUCKET_NAME=${GCP_BUCKET_NAME:-}
    volumes:
      - storage:/app/storage
      - logs:/app/logs
      - ${GCP_SA_CREDENTIALS:-/dev/null}:${GCP_SA_CREDENTIALS:-/dev/null}:ro
    networks:
      - app-network
    restart: unless-stopped

volumes:
  storage:
    driver: local
  logs:
    driver: local

networks:
  app-network:
    driver: bridge
