version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - API_KEY=${API_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_DOMAIN=${APP_DOMAIN}
      - APP_NAME=${APP_NAME}
      - APP_URL=${APP_URL}
      - DEFAULT_PLACEHOLDER_VIDEO=${DEFAULT_PLACEHOLDER_VIDEO}
      - GCP_BUCKET_NAME=${GCP_BUCKET_NAME}
      - GCP_SA_CREDENTIALS=${GCP_SA_CREDENTIALS}
      - GUNICORN_TIMEOUT=${GUNICORN_TIMEOUT}
      - GUNICORN_WORKERS=${GUNICORN_WORKERS}
      - LOCAL_STORAGE_PATH=${LOCAL_STORAGE_PATH}
      - PEXELS_API_KEY=${PEXELS_API_KEY}
      - PIXABAY_API_KEY=${PIXABAY_API_KEY}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - S3_REGION=${S3_REGION}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
    volumes:
      - storage:/app/storage
      - logs:/app/logs
      - gcp-sa-credentials:/app/gcp-sa-credentials
      - tmp-assets:/tmp
    networks:
      - app-network
    restart: unless-stopped

volumes:
  storage:
    driver: local
  logs:
    driver: local
  gcp-sa-credentials:
    driver: local
  tmp-assets:
    driver: local

networks:
  app-network:
    driver: bridge
