version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - MAX_QUEUE_LENGTH=100
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - app-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_ORIGINS=*
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:11434/api/tags || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  init-ollama:
    image: busybox:latest
    command: |
      sh -c '
      echo "Waiting for Ollama to be ready..."
      until wget -q --spider http://ollama:11434/api/tags; do
        sleep 2
      done
      echo "Ollama is ready"
      echo "Pulling Gemma 1B model..."
      wget --post-data="{\"name\": \"gemma3:1b\"}" --header="Content-Type: application/json" -O - http://ollama:11434/api/pull
      echo "Setup complete!"
      '
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - app-network

volumes:
  ollama_data:
    driver: local

networks:
  app-network:
    driver: bridge
