version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped

  api:
    depends_on:
      redis:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - python:3.10-slim
        - linuxserver/ffmpeg:latest
      args:
        BUILDKIT_INLINE_CACHE: 1
    shm_size: '2gb'
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
        reservations:
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/toolkit/test"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "8080:8080"
    environment:
      - API_KEY=${API_KEY}
      - APP_DEBUG=false
      - APP_DOMAIN=${APP_DOMAIN}
      - APP_NAME=${APP_NAME}
      - APP_URL=${APP_URL}
      - DEFAULT_PLACEHOLDER_VIDEO=${DEFAULT_PLACEHOLDER_VIDEO}
      - GCP_BUCKET_NAME=${GCP_BUCKET_NAME}
      - GCP_SA_CREDENTIALS=${GCP_SA_CREDENTIALS}
      - GUNICORN_TIMEOUT=${GUNICORN_TIMEOUT}
      - GUNICORN_WORKERS=${GUNICORN_WORKERS:-4}
      - LOCAL_STORAGE_PATH=${LOCAL_STORAGE_PATH}
      - PEXELS_API_KEY=${PEXELS_API_KEY}
      - PIXABAY_API_KEY=${PIXABAY_API_KEY}
      - RQ_WORKERS=${RQ_WORKERS:-4}
      - REDIS_URL=redis://redis:6379
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - S3_REGION=${S3_REGION}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
    volumes:
      - storage:/app/storage
      - logs:/app/logs
      - gcp-sa-credentials:/app/gcp-sa-credentials
      - tmp-assets:/tmp
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
    networks:
      - app-network
    restart: unless-stopped

  short-creator:
    build:
      context: ./short-video-maker
      dockerfile: main.Dockerfile
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
        reservations:
          memory: 2G
    ports:
      - "3123:3123"
    environment:
      - DEV=false
      - NODE_ENV=production
      - DAHOPEVI_API_KEY=${API_KEY}
      - DAHOPEVI_BASE_URL=http://api:8080
      - PEXELS_API_KEY=${PEXELS_API_KEY}
      - PIXABAY_API_KEY=${PIXABAY_API_KEY}
      - CONCURRENCY=2
      - VIDEO_CACHE_SIZE_IN_BYTES=2097152000
    volumes:
      - storage:/app/storage
      - tmp-assets:/tmp
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3123/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped

volumes:
  storage:
    driver: local
  logs:
    driver: local
  gcp-sa-credentials:
    driver: local
  tmp-assets:
    driver: local

networks:
  app-network:
    driver: bridge
    name: dahopevi_network
