version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: dahopevi-redis
    command: redis-server --bind 0.0.0.0 --protected-mode no --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - dahopevi-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      API_KEY: ${API_KEY:-}
      APP_DEBUG: 'false'
      APP_DOMAIN: ${APP_DOMAIN}
      APP_NAME: ${APP_NAME}
      APP_URL: ${APP_URL}
      DEFAULT_PLACEHOLDER_VIDEO: ${DEFAULT_PLACEHOLDER_VIDEO}
      GCP_BUCKET_NAME: ${GCP_BUCKET_NAME}
      GCP_SA_CREDENTIALS: ${GCP_SA_CREDENTIALS}
      GUNICORN_TIMEOUT: ${GUNICORN_TIMEOUT:-300}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS:-2}
      LOCAL_STORAGE_PATH: ${LOCAL_STORAGE_PATH}
      PEXELS_API_KEY: ${PEXELS_API_KEY}
      PIXABAY_API_KEY: ${PIXABAY_API_KEY}
      REDIS_URL: redis://redis:6379/0
      RQ_WORKERS: ${RQ_WORKERS:-2}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
      S3_REGION: ${S3_REGION}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      WHISPER_CACHE_DIR: /opt/whisper_cache
      TTS_SERVER_URL: ${TTS_SERVER_URL:-https://tts.dahopevi.com/api}
    volumes:
      - whisper_models:/opt/whisper_cache
      - dahopevi_data:/app/data
      - gcp-sa-credentials:/app/gcp-sa-credentials
      - tmp-assets:/tmp
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - dahopevi-network
    logging:
      driver: json-file
      options:
        max-size: "200m"
        max-file: "3"

  postiz:
    image: ghcr.io/gitroomhq/postiz-app:latest
    container_name: postiz
    restart: unless-stopped
    environment:
      MAIN_URL: ${YOUR_DOMAIN}
      FRONTEND_URL: ${YOUR_DOMAIN}
      NEXT_PUBLIC_BACKEND_URL: ${YOUR_DOMAIN}/api
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${SUPABASE_DATABASE_URL}
      REDIS_URL: redis://redis:6379/0
      BACKEND_INTERNAL_URL: http://localhost:3000
      IS_GENERAL: 'true'
      STORAGE_PROVIDER: local
      YOUTUBE_CLIENT_ID: ${YOUTUBE_CLIENT_ID}
      YOUTUBE_CLIENT_SECRET: ${YOUTUBE_CLIENT_SECRET}
      X_API_KEY: ${POSTIZ_X_API_KEY}
      X_API_SECRET: ${POSTIZ_X_API_SECRET}
      TIKTOK_CLIENT_ID: ${TIKTOK_CLIENT_ID}
      TIKTOK_CLIENT_SECRET: ${TIKTOK_CLIENT_SECRET}
      THREADS_APP_ID: ${THREADS_APP_ID}
      THREADS_APP_SECRET: ${THREADS_APP_SECRET}
      TELEGRAM_BOT_NAME: ${TELEGRAM_BOT_NAME}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      SLACK_ID: ${SLACK_ID}
      SLACK_SECRET: ${SLACK_SECRET}
      REDDIT_CLIENT_ID: ${REDDIT_CLIENT_ID}
      REDDIT_CLIENT_SECRET: ${REDDIT_CLIENT_SECRET}
      PINTEREST_CLIENT_ID: ${PINTEREST_CLIENT_ID}
      PINTEREST_CLIENT_SECRET: ${PINTEREST_CLIENT_SECRET}
      MASTODON_CLIENT_ID: ${MASTODON_CLIENT_ID}
      MASTODON_CLIENT_SECRET: ${MASTODON_CLIENT_SECRET}
      LINKEDIN_CLIENT_ID: ${LINKEDIN_CLIENT_ID}
      LINKEDIN_CLIENT_SECRET: ${LINKEDIN_CLIENT_SECRET}
      FACEBOOK_APP_ID: ${FACEBOOK_APP_ID}
      FACEBOOK_APP_SECRET: ${FACEBOOK_APP_SECRET}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      INSTAGRAM_APP_ID: ${INSTAGRAM_APP_ID}
      INSTAGRAM_APP_SECRET: ${INSTAGRAM_APP_SECRET}
    ports:
      - "5000:5000"
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - postiz-config:/config
      - postiz-uploads:/uploads
    networks:
      - dahopevi-network

volumes:
  whisper_models:
    driver: local
  dahopevi_data:
    driver: local
  gcp-sa-credentials:
    driver: local
  tmp-assets:
    driver: local
  postiz-config:
    driver: local
  postiz-uploads:
    driver: local
  redis_data:
    driver: local

networks:
  dahopevi-network:
    driver: bridge
