version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: dahopevi-redis
    command: redis-server --bind 0.0.0.0 --protected-mode no --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - dahopevi-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      # Mount source code for live reload during development
      - .:/app
      # Exclude cache and build directories
      - /app/__pycache__
      - /app/.pytest_cache
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - dahopevi-network

volumes:
  redis_data:
    driver: local

networks:
  dahopevi-network:
    driver: bridge