version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - MAX_QUEUE_LENGTH=100
    depends_on:
      - ollama
    networks:
      - app-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network
    # This healthcheck ensures Ollama is ready before API starts
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 5

  init-ollama:
    image: curlimages/curl:latest
    command: |
      sh -c '
      echo "Waiting for Ollama to be ready..."
      until curl -s -f "http://ollama:11434/api/tags" > /dev/null 2>&1; do
        sleep 2
      done
      echo "Ollama is ready"
      echo "Pulling Qwen 1.7B model..."
      curl -X POST http://ollama:11434/api/pull -d "{\"name\": \"qwen:1.7b\"}"
      echo "Setup complete!"
      '
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - app-network

volumes:
  ollama_data:
    driver: local

networks:
  app-network:
    driver: bridge
