services:
  postiz:
    image: 'ghcr.io/gitroomhq/postiz-app:latest'
    container_name: postiz
    restart: always
    environment:
      MAIN_URL: '${YOUR_DOMAIN}'
      FRONTEND_URL: '${YOUR_DOMAIN}'
      NEXT_PUBLIC_BACKEND_URL: '${YOUR_DOMAIN}/api'
      JWT_SECRET: '${JWT_SECRET}'
      DATABASE_URL: 'postgresql://postiz-user:postiz-password@postiz-postgres:5432/postiz-db-local'
      REDIS_URL: 'redis://postiz-redis:6379'
      BACKEND_INTERNAL_URL: 'http://localhost:3000'
      IS_GENERAL: 'true'
      STORAGE_PROVIDER: local
      UPLOAD_DIRECTORY: /uploads
      NEXT_PUBLIC_UPLOAD_DIRECTORY: /uploads
      YOUTUBE_CLIENT_ID: '${YOUTUBE_CLIENT_ID}'
      YOUTUBE_CLIENT_SECRET: '${YOUTUBE_CLIENT_SECRET}'
      X_API_KEY: '${X_API_KEY}'
      X_API_SECRET: '${X_API_SECRET}'
      TIKTOK_CLIENT_ID: '${TIKTOK_CLIENT_ID}'
      TIKTOK_CLIENT_SECRET: '${TIKTOK_CLIENT_SECRET}'
      THREADS_APP_ID: '${THREADS_APP_ID}'
      THREADS_APP_SECRET: '${THREADS_APP_SECRET}'
      TELEGRAM_BOT_NAME: '${TELEGRAM_BOT_NAME}'
      TELEGRAM_TOKEN: '${TELEGRAM_TOKEN}'
      SLACK_ID: '${SLACK_ID}'
      SLACK_SECRET: '${SLACK_SECRET}'
      REDDIT_CLIENT_ID: '${REDDIT_CLIENT_ID}'
      REDDIT_CLIENT_SECRET: '${REDDIT_CLIENT_SECRET}'
      PINTEREST_CLIENT_ID: '${PINTEREST_CLIENT_ID}'
      PINTEREST_CLIENT_SECRET: '${PINTEREST_CLIENT_SECRET}'
      MASTODON_CLIENT_ID: '${MASTODON_CLIENT_ID}'
      MASTODON_CLIENT_SECRET: '${MASTODON_CLIENT_SECRET}'
      LINKEDIN_CLIENT_ID: '${LINKEDIN_CLIENT_ID}'
      LINKEDIN_CLIENT_SECRET: '${LINKEDIN_CLIENT_SECRET}'
      FACEBOOK_APP_ID: '${FACEBOOK_APP_ID}'
      FACEBOOK_APP_SECRET: '${FACEBOOK_APP_SECRET}'
      DISCORD_CLIENT_ID: '${DISCORD_CLIENT_ID}'
      DISCORD_CLIENT_SECRET: '${DISCORD_CLIENT_SECRET}'
      INSTAGRAM_APP_ID: '${INSTAGRAM_APP_ID}'
      INSTAGRAM_APP_SECRET: '${INSTAGRAM_APP_SECRET}'
    volumes:
      - 'postiz-config:/config/'
      - 'postiz-uploads:/uploads/'
    ports:
      - '5000:5000'
    networks:
      - postiz-network
    labels:
      - traefik.enable=true
    depends_on:
      postiz-postgres:
        condition: service_healthy
      postiz-redis:
        condition: service_healthy
  postiz-postgres:
    image: 'postgres:14.5'
    container_name: postiz-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postiz-password
      POSTGRES_USER: postiz-user
      POSTGRES_DB: postiz-db-local
    volumes:
      - 'postgres-volume:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    networks:
      - postiz-network
    healthcheck:
      test: 'pg_isready -U postiz-user -d postiz-db-local'
      interval: 10s
      timeout: 3s
      retries: 3
  postiz-redis:
    image: 'redis:7.2'
    container_name: postiz-redis
    restart: always
    ports:
      - '6379:6379'
    healthcheck:
      test: 'redis-cli ping'
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - 'postiz-redis-data:/data'
    networks:
      - postiz-network
volumes:
  postgres-volume:
    external: false
  postiz-redis-data:
    external: false
  postiz-config:
    external: false
networks:
  postiz-network:
    external: false
